name: Release
on:
  push:
    branches: [ main ]
env:
  AWS_REGION: ap-northeast-2
jobs:
  build:
    name: Chart release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/Chart.yaml

      - name: print diff
        run: echo ${{ env.GIT_DIFF }}

      - name: Helm release
        uses: shellbear/helm-release-action@0.1
        if: contains(${{ env.GIT_DIFF}}, 'joybox-app')
        with:
          repo: s3://joybox-helm-charts
          chart: ./joybox-app